from . import res_partner
from . import sale_order
from . import invoice
from . import helpdesk
from . import timesheet
from . import ticket_remarks
from . import rso_battery
from . import oc_requisition
from . import oc_requisition_line
from . import stock_picking