# -*- coding: utf-8 -*-
{
    'name': 'Oc Mutual Bank Customization',
    'version': '1.1',
    'category': 'Productivity',
    'sequence': 30,
    'summary': 'Oc Mutual Bank Customization',
    'description': """Oc Mutual Bank Customization""",
    'website': 'https://www.odooconcepts.com',
    'license': 'LGPL-3',
    'depends': ['base','sale_management','account_accountant','helpdesk','oc_ufone_sms_api_integration','hr','stock'],
    'data': [
        'security/rso_security.xml',
        'security/ir.model.access.csv',
        'data/mutual_bank_sequence.xml',
        'report/mutual_bank_reports.xml',
        'report/report_customer_inventory.xml',
        'report/report_technician_inventory.xml',
        'views/res_partner.xml',
        'views/sale_order.xml',
        'views/invoice.xml',
        'views/helpdesk.xml',
        'views/rso_battery.xml',
        'views/oc_requisition.xml',
        'views/oc_requisition_line.xml',
        'views/stock_picking.xml',
        'wizard/inventory_wizard_view.xml',

    ],
    'qweb': [],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
